# Blueprint for deploying the Google Review Analyzer on Render.

services:
  - type: web
    name: review-analyzer
    env: python
    plan: free # Use the free instance type
    buildCommand: "chmod +x render-build.sh && ./render-build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: SERPAPI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDER_EMAIL
        sync: false
