# Blueprint for deploying the Google Review Analyzer on Render.

services:
  - type: web
    name: review-analyzer
    env: docker
    plan: free # Use the free instance type
    dockerfilePath: ./Dockerfile
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT main:app"
    envVars:
      - key: SERPAPI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDER_EMAIL
        sync: false
